name: Snapshots Check

on:
  schedule:
    - cron: "0 20 * * *"
permissions: read-all
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [ 3.5.x, main ]
        test-type:
          - type: fast
            arguments: ":reactor-core:test --no-daemon -Pjunit-tags=!slow -DuseSnapshotMicrometerVersion=true"
          - type: slow
            arguments: ":reactor-core:test --no-daemon -Pjunit-tags=slow -DuseSnapshotMicrometerVersion=true"
          - type: other
            arguments: "check -x :reactor-core:test -x spotlessCheck -x :reactor-core:jcstress --no-daemon -DuseSnapshotMicrometerVersion=true -Pjcstress.mode=default"
    name: Test on ${{ matrix.branch }} - ${{ matrix.test-type.type }} tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # tag=v4
        with:
          ref: ${{ matrix.branch }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Run Gradle Tests
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: ${{ matrix.test-type.arguments }}
