name: Snapshots Check

on:
#  schedule:
#    - cron: "0 20 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: [ main, main ]
        test-type: [fast, slow, other]
    name: Test on ${{ matrix.branch }} - ${{ matrix.test-type }} tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Run Gradle Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            ${{ if eq(matrix.test-type, 'fast') }} 
              :test --no-daemon -Pjunit-tags=!slow -DuseSnapshotMicrometerVersion=true
            ${{ else if eq(matrix.test-type, 'slow') }} 
              :test --no-daemon -Pjunit-tags=slow -DuseSnapshotMicrometerVersion=true
            ${{ else if eq(matrix.test-type, 'other') }} 
              check -x :test --no-daemon -DuseSnapshotMicrometerVersion=true -Pjcstress.mode=default
